### PR TITLE
Add slash to the URL in examples

### PR DESCRIPTION
**Pull request by dpschen**
https://forum.getkirby.com/t/uniform-form-not-working/3213/7

### CODE REVIEW

**Comment by mzur** [comment]
I'm not sure about this. Some configurations do the redirect, some don't. Some do it the other way around so the examples will no longer work after the PR. Kirby doesn't do any of these redirects by default.

Do you have any resources on which behavior is the standard™ way?

**Comment by dpschen** [comment]
Good question. I just got caught on fixing this issue for my form.
Maybe it has to do something with my .htaccess configuration.
I use this one: https://github.com/h5bp/server-configs-apache
+ some kirby specific stuff.

Perhaps it's best to add here a note as well.

**Comment by dpschen** [comment]
Sorry I just saw that you already wrote this in the wiki: https://github.com/mzur/kirby-uniform/wiki/Answers

**Comment by mzur** [comment]
Yeah, I was about to mention that, too. Maybe I should highlight the "Questions?" part in the readme some more. I'll close this PR then if you're ok with it.

**Comment by dpschen** [comment]
Yes that would be a good solution.

**Pull request closed without merging**
