### PR TITLE
fix invocation of static action & guard callbacks

### PR DESCRIPTION
**Pull request by fetzi**
Fix for encountered problems during recaptcha plugin development (Undefined index ...)

### CODE REVIEW

**Comment by mzur** [comment]
What error did you get exactly? There is always a check if the array element exists so there shouldn't be an undefined index.

**Comment by fetzi** [comment]
Undefined index: recaptcha in UniForm.php on line 207 and
Function name must be a string in UniForm.php on line 207

The method call with __invoke resolves the problem. Same error for static::$actions callback

**Comment by mzur** [comment]
Shouldn't it rather be line 223? What does your line 207 look like? The error is very odd since `array_key_exists` is called just before.

Does it work using `call_user_func(static::$guards[$guard], $this)`?

**Comment by fetzi** [comment]
sorry for the line mixup ;-)

For line 223: `$check = call_user_func(static::$guards[$guard], $this);`
For line 320: `$this->actionOutput[$index] = call_user_func(static::$actions[$key], $this->data, $action);`

Both invocations are working

**Comment by mzur** [comment]
Then please change your PR to use `call_user_func` and I'll merge. Strange, since I'm getting no error at all...

**Comment by fetzi** [comment]
here you go

**Comment by mzur** [comment]
For the actions invocation as well if you don't mind :wink:

**Comment by fetzi** [comment]
done

**Comment by mzur** [comment]
Thanks :+1:

**Pull request merged**
