### PR TITLE
Kirby 4 Support

### LINKED ISSUE #250: [K4] Issue with form submission
## Description
When submitting a form, I am getting an error in the PHP log and the form is failing to submit

**Expected behavior**  
A successful form submission. This setup was working in the latest stable v3 version of Kirby

## To reproduce

1. Set up Kirby V4, and add the Uniform plugin
2. Create a simple form, use Uniform to handle the submission

## Your setup
**Kirby Version**  
Kirby 4 Beta 1

**PHP Error Log**
```
[11-Sep-2023 21:19:50 UTC] TypeError: Kirby\Toolkit\Str::template(): Argument #3 ($options) must be of type array, string given, called in /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Actions/EmailAction.php on line 124 and defined in /Users/mike/Dropbox/boilerplate/kirby/src/Toolkit/Str.php:1244
Stack trace:
#0 /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Actions/EmailAction.php(124): Kirby\Toolkit\Str::template('New form submis...', Array, '')
#1 /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Actions/EmailAction.php(134): Uniform\Actions\EmailAction->resolveTemplate('New form submis...')
#2 /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Actions/EmailAction.php(38): Uniform\Actions\EmailAction->getSubject()
#3 /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Form.php(284): Uniform\Actions\EmailAction->perform()
#4 /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Form.php(207): Uniform\Form->perform(Object(Uniform\Actions\EmailAction))
#5 /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Form.php(253): Uniform\Form->action(Object(Uniform\Actions\EmailAction), Array)
#6 /Users/mike/Dropbox/boilerplate/site/controllers/default.php(80): Uniform\Form->__call('emailAction', Array)
#7 [internal function]: Kirby\Cms\App->{closure}(Object(Kirby\Cms\App), Object(Kirby\Cms\Page), Object(Kirby\Cms\Site))
#8 /Users/mike/Dropbox/boilerplate/kirby/src/Toolkit/Controller.php(58): Closure->call(Object(Kirby\Cms\App), kirby: Object(Kirby\Cms\App), page: Object(Kirby\Cms\Page), site: Object(Kirby\Cms\Site))
#9 /Users/mike/Dropbox/boilerplate/kirby/src/Cms/App.php(450): Kirby\Toolkit\Controller->call(Object(Kirby\Cms\App), Array)
#10 /Users/mike/Dropbox/boilerplate/kirby/src/Cms/Page.php(316): Kirby\Cms\App->controller('default', Array, 'html')
#11 /Users/mike/Dropbox/boilerplate/kirby/src/Cms/Page.php(996): Kirby\Cms\Page->controller(Array, 'html')
#12 /Users/mike/Dropbox/boilerplate/kirby/src/Cms/App.php(776): Kirby\Cms\Page->render()
#13 /Users/mike/Dropbox/boilerplate/kirby/src/Cms/App.php(1190): Kirby\Cms\App->io(Object(Kirby\Cms\Page))
#14 /Users/mike/Dropbox/Boilerplate/index.php(5): Kirby\Cms\App->render()  
```

Author @MikeHarrison from https://github.com/getkirby/kirby/issues/5618

### PR DESCRIPTION
**Pull request by mzur**
Resolves #250

### CODE REVIEW

**Comment by MikeHarrison** [comment]
Thanks for taking a look at this. If you want anyone to test it out I would be happy to help.

**Comment by mzur** [comment]
@MikeHarrison Thanks for offering to take a look. I've now released v5.5.0-beta with Kirby 4 support from this PR. Please test away :wink:

**Comment by MikeHarrison** [comment]
Hi! Thanks for this. I have swapped in this Beta on my boilerplate, but am getting an error (this is probably something I am doing wrong!)

```
Error thrown with message "Failed opening required '/Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/Applications/MAMP/bin/php/php8.1.0/lib/php')"

Stacktrace:
#11 Error in /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/vendor/composer/autoload_real.php:53
#10 composerRequire979ccd9ac382cfbe433fc1293b41c6ce in /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/vendor/composer/autoload_real.php:36
#9 ComposerAutoloaderInit979ccd9ac382cfbe433fc1293b41c6ce:getLoader in /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/vendor/autoload.php:12
#8 include_once in /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/index.php:5
#7 include_once in /Users/mike/Dropbox/boilerplate/kirby/src/Filesystem/F.php:440
#6 Kirby\Filesystem\F:Kirby\Filesystem\{closure} in /Users/mike/Dropbox/boilerplate/kirby/src/Http/Response.php:211
#5 Kirby\Http\Response:guardAgainstOutput in /Users/mike/Dropbox/boilerplate/kirby/src/Filesystem/F.php:443
#4 Kirby\Filesystem\F:loadOnce in /Users/mike/Dropbox/boilerplate/kirby/src/Cms/AppPlugins.php:784
#3 Kirby\Cms\App:pluginsLoader in /Users/mike/Dropbox/boilerplate/kirby/src/Cms/AppPlugins.php:751
#2 Kirby\Cms\App:plugins in /Users/mike/Dropbox/boilerplate/kirby/src/Cms/AppPlugins.php:640
#1 Kirby\Cms\App:extensionsFromPlugins in /Users/mike/Dropbox/boilerplate/kirby/src/Cms/App.php:144
#0 Kirby\Cms\App:__construct in /Users/mike/Dropbox/Boilerplate/index.php:5
```

**Comment by MikeHarrison** [comment]
Got it installed, working perfectly! Thank you!

**Pull request merged**
