### PR TITLE
Add composer version for 3.8 update check

### PR DESCRIPTION
**Pull request by afbora**

### CODE REVIEW

**Comment by mzur** [comment]
I don't know if I like this new requirement. It forces me to update the composer.json each time I want to do a release (including the possibility that I forget it). Also, Composer itself does not like it (as the PR checks tell). @lukasbestle [Said](https://github.com/mzur/kirby-uniform/pull/227#issuecomment-1258460469) that Kirby might implement a version check based on the Composer files. I'd rather like to wait for that feature.

**Comment by afbora** [comment]
I have no idea how to do version control without version information in composer.json. The current system checks the version in composer.json.

**Comment by afbora** [comment]
If you want to wait for a future development, that's your decision 👍

**Comment by mzur** [comment]
> I have no idea how to do version control without version information in composer.json.

In a Composer setup there is a file `vendor/composer/installed.php` which can be easily read and contains all the versions of the installed packages. But of course this does not work with Kirby's approach of copying plugins in `site/plugins`...

**Comment by lukasbestle** [comment]
Both the planned feature to read version information from the `vendor` dir and the current behavior are independent from the installation path (`site/plugins` or `vendor`). Kirby's Composer installer installs the plugin to `site/plugins`, but Composer will still put the version information in `vendor/composer/installed.php`. As I wrote before, we plan to support version retrieval from this file soon.

Even with this feature, the advantage of including the `version` key in `composer.json` is that the version number will also be available when the plugin is downloaded as ZIP file or installed as Git submodule.

I get your points that Composer advises against using the `version` key and that it can be forgotten to update the value on release. Unfortunately we haven't found a better solution that works for all three ways to install a Kirby plugin. If you have a suggestion, please let us know.

As Ahmet wrote, it is of course your decision if you want to merge or close this PR.

**Comment by mzur** [comment]
I'll close this in favor of https://github.com/getkirby/kirby/issues/4733. I strongly prefer the Composer installation method.

**Pull request closed without merging**
